highlighter: rouge
markdown: kramdown
exclude: ["README.md"]
url: https://stevetotheizz0.github.io
baseurl: /blog
gems: [jekyll-paginate]
plugins_dir: [jekyll-paginate]
paginate: 6
paginate_path: "page:num"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
